config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'pages#home'
  get 'about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2, maximum: 100 }
  validates :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book_by_id, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(getting_book_params)
    if @book.save
      flash[:notice] = 'Book was created successfully.'
      redirect_to @book
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @book.update(getting_book_params)
    if @book.save
      flash[:notice] = 'Book was updated successfully.'
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def find_book_by_id
    @book = Book.find(params[:id])
  end

  def getting_book_params
    params.require(:book).permit(:title, :author)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_errors.html.erb
<% if @book.errors.any? %>
  <h2>The following errors prevented the book from being saved: </h2>
  <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/books/_form.html.erb
<%= form_with(model: @book, local: true) do |f| %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/books/edit.html.erb
<h1>Edit book</h1>

<%= render 'errors' %>
<%= render 'form' %>

<%= link_to 'Cancel Edit', books_path %>

app/views/books/index.html.erb
<h1>Index page</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= link_to 'Show', book_path(book), method: :get %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure you want to delete this book?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Create New Book', new_book_path %>

app/views/books/new.html.erb
<h1>Create a new book</h1>

<%= render 'errors' %>
<%= render 'form' %>

<%= link_to 'Home', books_path %>

app/views/books/show.html.erb
<h1>Showing book details</h1>

<p><strong>Title: <%= @book.title %> </strong></p>

<p><strong>Author: <%= @book.author %></strong></p>


<%= link_to 'Home', books_path %> |
<%= link_to 'Edit', edit_book_path %> |
<%= link_to 'Delete', book_path(@book), method: :delete, data: { confirm: 'Are you sure you want to delete this book?' } %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryAppV2</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/messages' %>
<%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

<%= link_to 'Home', root_path %>
<%= link_to 'Books Listing', books_path %>

app/views/pages/home.html.erb
<h1>Hello world!</h1>

<%= link_to 'Books Listing', books_path %>
<%= link_to 'About', about_path %>